-- MySQL Script generated by MySQL Workbench
-- Tue Jan 21 21:28:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CombaDashboardDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CombaDashboardDB` ;

-- -----------------------------------------------------
-- Schema CombaDashboardDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CombaDashboardDB` DEFAULT CHARACTER SET utf8 ;
USE `CombaDashboardDB` ;

-- -----------------------------------------------------
-- Table `CombaDashboardDB`.`SOFTWARE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CombaDashboardDB`.`SOFTWARE` ;

CREATE TABLE IF NOT EXISTS `CombaDashboardDB`.`SOFTWARE` (
  `id_soft` INT UNSIGNED AUTO_INCREMENT,
  `nom_soft` VARCHAR(80) NOT NULL,
  `desc_soft` VARCHAR(200) NOT NULL,
  `fec_soft` DATE NOT NULL,
  PRIMARY KEY (`id_soft`),
  UNIQUE INDEX `id_soft_UNIQUE` (`id_soft` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CombaDashboardDB`.`AUTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CombaDashboardDB`.`AUTOR` ;

CREATE TABLE IF NOT EXISTS `CombaDashboardDB`.`AUTOR` (
  `id_aut` INT UNSIGNED AUTO_INCREMENT,
  `ced_aut` VARCHAR(11) NOT NULL,
  `nom_aut` VARCHAR(50) NOT NULL,
  `ape_aut` VARCHAR(50) NOT NULL,
  `sex_aut` CHAR(1) NOT NULL COMMENT 'M: Masculino\nF: Femenino',
  `cel_aut` VARCHAR(10) NOT NULL,
  `email_aut` VARCHAR(50) NOT NULL,
  `niv_acad_aut` VARCHAR(9) NOT NULL COMMENT 'Tecnológo\nPregrado\nMaestria\nDoctorado\nPhD',
  `ciud_aut` VARCHAR(20) NOT NULL COMMENT 'TABLA CIUDADES',
  `num_cvlac_aut` VARCHAR(10) NULL,
  `rol_aut` VARCHAR(25) NOT NULL COMMENT 'Semillero\nEstudiante Investigador\nProfesor Investigador',
  `estado_aut` VARCHAR(8) NOT NULL COMMENT 'Activo\nInactivo',
  `admin_aut` TINYINT(1) NOT NULL COMMENT '0: no admin\n1: admin',
  PRIMARY KEY (`id_aut`),
  UNIQUE INDEX `id_aut_UNIQUE` (`id_aut` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CombaDashboardDB`.`DESARROLLO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CombaDashboardDB`.`DESARROLLO` ;

CREATE TABLE IF NOT EXISTS `CombaDashboardDB`.`DESARROLLO` (
  `id_des` INT UNSIGNED AUTO_INCREMENT,
  `id_aut` INT UNSIGNED NOT NULL,
  `id_soft` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_des`),
  INDEX `id_soft_idx` (`id_soft` ASC) VISIBLE,
  INDEX `id_aut_idx` (`id_aut` ASC) VISIBLE,
  UNIQUE INDEX `id_des_UNIQUE` (`id_des` ASC) VISIBLE,
  CONSTRAINT `id_soft`
    FOREIGN KEY (`id_soft`)
    REFERENCES `CombaDashboardDB`.`SOFTWARE` (`id_soft`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `id_aut`
    FOREIGN KEY (`id_aut`)
    REFERENCES `CombaDashboardDB`.`AUTOR` (`id_aut`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
